name: Build & Deploy
concurrency: frontend-deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options:
          - production
jobs:
   build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      #- name: Test
      #  run: npm run test:prod && npm run build
      
      #- name: Coverage
      #  run: npm run coverage
      
      - name: Build docs
        run: npm run build:docs

      - name: Deploy docs
        run: |
          cd docs
          git init
          git config user.name "Tillhub Engineer"
          git config user.email "engineering@tillhub.de"
          git add .
          git commit -m "docs(docs): update gh-pages [ci skip]"
          git push --force --quiet "https://${{ secrets.GH_TOKEN }}@github.com/tillhub/tillhub-sdk-javascript.git" master:gh-pages

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release || true
      
